version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: honours-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "honoursDatabase"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./ddl:/docker-entrypoint-initdb.d
volumes:
  mysql-db:
